In [0]:
import numpy as np

# Vetores

In [24]:
# Multiplicação de array por escalar
x = np.array([2,2,2,2])
y = 3

print(x*y)

[6 6 6 6]


In [25]:
# Multiplicação de array
x = np.array([2,2,2,2,2])
y = np.array([3,3,3,3,3])

print(x*y)

[6 6 6 6 6]


In [8]:
# Multiplicação de array com broadcast Numpy com vetores de tamanhos diferentes, com menor vetor de tamanho 1;
x = np.array([2,2,2,2])
y = np.array([3])

print(x*y)

[6 6 6 6]


In [26]:
# Multiplicação de array com broadcast Numpy com vetores de tamanhos diferentes, com menor vetor com tamanho maior que 1;
# Erro
x = np.array([2,2,2,2])
y = np.array([3,4])

print(x*y)

ValueError: ignored

# Matrizes

Dica:
Visualizar matriz como uma lista de listas. Os elementos de primeiro nível são as linhas, e os de segundo são as colunas;


In [21]:
# Multiplicação de Matriz por escalar

x = np.array([[2,2], [3,3], [4,4]])
y = 4

print(x*y)

[[ 8  8]
 [12 12]
 [16 16]]


In [28]:
# Multiplicação de Matriz por vetor

x = np.array([[2,2], [3,3], [4,4]])
y = np.array([5])

print(x*y)

[[10 10]
 [15 15]
 [20 20]]


In [33]:
# Multiplicação de Matriz por vetor com erro de broadcast.
# Erro de broadcast
# Motivo: Vetor possui tamanho maior que 1 e diferente do tamanho da matriz.

x = np.array([[2,2], [3,3], [4,4]])
y = np.array([5,2,3])

print(x*y)

ValueError: ignored

In [38]:
# Multiplicação de Matriz por vetor sem erro de broadcast.
# Sem erro
# Motivo: Numpy identificou o y como uma matriz de um único elemento.
# Observação: Esse é um exemplo de que o broadcast resolve, porém as vezes não era o resultado esperado. 
#             As vezes a intenção de y ter 2 elementos não seja identificá-lo como uma matriz.
x = np.array([[2,2], [3,3], [4,4]])
y = np.array([5,10])

print(x.shape)
print(y.shape)
print()
print(x*y)

(3, 2)
(2,)

[[10 20]
 [15 30]
 [20 40]]


# Tensores

Dica: Visualizar como lista de matrizes;

In [62]:
x = np.array([
    [["m1_l1_c1","m1_l1_c2"],["m1_l2_c1","m1_l2_c2"],["m1_l3_c1","m1_l3_c2"]], 
    [["m2_l1_c1","m2_l1_c2"],["m2_l2_c1","m2_l2_c2"],["m2_l3_c1","m2_l3_c2"]], 
    [["m3_l1_c1","m3_l1_c2"],["m3_l2_c1","m3_l2_c2"],["m3_l3_c1","m3_l3_c2"]], 
])

print(x.shape)

(3, 3, 2)


Visualizando posições de um tensor:
> Para facilitar a visualização, cada elemento tem sua posição:
>> Exemplo: "m1_l3_c1"
>> * m1 = 1ª matriz
>> * l3 = 3ª linha
>> * c1 = 1ª coluna


In [64]:
# Busca por level
print("Segunda matriz:")
print(x[1])
print()

# Busca por level e linha
print("Terceira linha da segunda matriz")
print(x[1][2])
print()

# Busca por level, linha e coluna
print("Primeira coluna da terceira linha da segunda matriz")
print(x[1][2][0])

Segunda matriz:
[['m2_l1_c1' 'm2_l1_c2']
 ['m2_l2_c1' 'm2_l2_c2']
 ['m2_l3_c1' 'm2_l3_c2']]

Terceira linha da segunda matriz
['m2_l3_c1' 'm2_l3_c2']

Primeira coluna da terceira linha da segunda matriz
m2_l3_c1


## Operações com tensores

In [68]:
# Multiplicação de tensor por escalar
x = np.array([
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
])

y = 3

print(x*y)

[[[ 6 12]
  [18 24]]

 [[ 6 12]
  [18 24]]

 [[ 6 12]
  [18 24]]]


In [77]:
# Multiplicação de tensor por vetor de tamanho igual ao elemento da matriz. 
# A multiplicação é feita por broadcast.
x = np.array([
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
])

y = np.array([2,3])

print(x*y)

# Multiplicar o tensor x pelo vetor y = [2,3] é o mesmo que multiplicar o mesmo tensor por:
# matriz = [[2,3]]
# tensor = [[[2,3]]]

[[[ 4 12]
  [12 24]]

 [[ 4 12]
  [12 24]]

 [[ 4 12]
  [12 24]]]


In [73]:
# Multiplicação de tensor por vetor maior que o último nível do array multi-dimensional, 
# ou seja, vetor maior que o tamanho do item da matriz.
# Erro
# Motivo: Não é possível broadcast.
x = np.array([
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
])

y = np.array([2,3,4])

print(x*y)

ValueError: ignored

In [79]:
# Multiplicação de tensor por matriz. 
x = np.array([
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
])

y = np.array([[2,3],[4,5]])

print(x.shape)
print(y.shape)
print()

print(x*y)

(3, 2, 2)
(2, 2)

[[[ 4 12]
  [24 40]]

 [[ 4 12]
  [24 40]]

 [[ 4 12]
  [24 40]]]


In [81]:
# Multiplicação de tensor por tensor. 
x = np.array([
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
    [[2,4],[6,8]], 
])

y = np.array([
    [[2,3],[4,5]], 
    [[6,7],[8,9]], 
    [[10,10],[10,10]]])

print(x.shape)
print(y.shape)
print()

print(x*y)

(3, 2, 2)
(3, 2, 2)

[[[ 4 12]
  [24 40]]

 [[12 28]
  [48 72]]

 [[20 40]
  [60 80]]]


# Fontes

https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/
